trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Inicia o Kafka e o Zookeeper em background usando Docker
- script: |
    docker network create kafka-net
    docker run -d --name zookeeper --network kafka-net -e ZOOKEEPER_CLIENT_PORT=2181 confluentinc/cp-zookeeper:latest
    docker run -d --name kafka --network kafka-net --ports 9092:9092 -e KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 confluentinc/cp-kafka:latest
  displayName: 'Iniciar Kafka no Docker'

# 2. Restaura as dependências do projeto
- script: dotnet restore
  displayName: 'Recuperar os pacotes'

# 3. Compila o código do projeto
- script: dotnet build
  displayName: 'Buildando o projeto'

# 4. Executa os testes automatizados integrados com o Kafka local
- script: dotnet test --no-build --verbosity normal
  displayName: 'Executar Testes de Integração'
